from os import environ


CREDENTIAL_ENVIRON_NAME = "VCNOTIFY_CRED"
DISCORD_TOKEN_ENVIRONMENT_NAME = "TOKEN"

CREDENTIAL_B64 = environ[CREDENTIAL_ENVIRON_NAME]
DISCORD_TOKEN = environ[DISCORD_TOKEN_ENVIRONMENT_NAME]

CREDENTIAL_FILE_NAME = "credential.json"
